blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.bloglistview.as_view(), name='bloglist'),
    path('<int:pk>', views.blogdetailview.as_view(), name='blogview'),
    
]

ourproject/urls.py
from atexit import register
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from login.views import loginpage,logoutpage
from registration.views import registerpage,accountsetting

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('075bct/', admin.site.urls),
    path('',loginpage,name='login'),
    path('registerpage/', registerpage,name="registerpage"),
    path('ac/',accountsetting,name='as'),
   ## path('',include('home.urls')),
    path('mainpage/',include('main.urls')),
       
    
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from destination.models import Places
from django.contrib.auth.models import User
import datetime
import os 
# Create your models here.

def th_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.title, 'blogthumbnail', ext)
    return os.path.join('blogthumbnails', filename)


class Blog(models.Model):
    title=models.CharField(max_length=50, blank=False, null = False )
    author=models.ForeignKey( User , on_delete=models.CASCADE)
    description=models.TextField(blank= False, null=False)
    thumbnail=models.ImageField(upload_to=th_file_name , null=False )
    created_date=models.DateField(auto_now_add=True)
    related_place=models.ForeignKey(Places,on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    class Meta:
        ordering=['-created_date']

def img_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.bg.title, 'blogimage', ext)
    return os.path.join('blogimages', filename)


class Blogimages(models.Model):
    bg=models.ForeignKey(Blog,on_delete=models.CASCADE)
    image=models.FileField(null=True,blank=True,upload_to=img_file_name)

    def __str__(self):
        return self.bg.title


 

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Blog, Blogimages

class blogviewform(ModelForm):
    class Meta:
        model= Blog
        fields=['title','description','author']         


class createblogpostform(ModelForm):
    class Meta:
        model=Blog
        fields=['title','thumbnail']

blog/views.py
from calendar import c
from inspect import BlockFinder
from django.shortcuts import redirect, render

from destination.models import Places
from .models import Blog, Blogimages
from django.views import generic
from .forms import createblogpostform
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required 

# Create your views here.
@method_decorator(login_required, name='dispatch')
class bloglistview(generic.ListView):
    model= Blog
    template_name= 'blog/blog_list.html'
    
    
class blogdetailview(generic.DetailView):
    model= Blog
    template_name= 'blog/blogpost_view.html'
    def get_context_data(self, *args, **kwargs):
        context = super(blogdetailview, self).get_context_data(*args, **kwargs)
        user=self.request.user
        context['images'] = Blogimages.objects.all()
       

        return context
       

@login_required
def add_blogview(request,p_id):
    if request.method=='POST':
        form=createblogpostform(request.POST or None,request.FILES or None)
        images=request.FILES.getlist('images')
        description = request.POST.get('post')
        if form.is_valid():
            data=Blog()
            data.related_place_id=p_id
            data.title=form.cleaned_data['title']
            data.description=description
            data.author=request.user
            data.thumbnail=form.cleaned_data['thumbnail']
            data.save()
            if(len(images)==0):
                Blogimages.objects.create(bg_id=data.id,image=data.thumbnail)
            else:
                for f in images:
                    Blogimages.objects.create(bg_id=data.id,image=f)
               
            
            return redirect('placeview' , p_id)   
            
    else:
        form=createblogpostform()
        
    return render(request,'blog/postblog.html',{'form':form , 'place': Places.objects.get(id=p_id)})          

     

blog/templates/blog/blog_list.html
{% extends "main.html" %}
{% load static %}
{% block title %}
Blogs 
{% endblock title %}

{% block myblock %}
<style>
  .myclass{
    background-color: none;
  }
</style>
<script src="https://cdn.tailwindcss.com"></script>
{% endblock myblock %}
{% block content %}

  {% if object_list %}
 <section style="padding-top:100px;">
    {% for blog in object_list %}
      
     <!--<a href="{% url 'blogview' blog.id %}"><img src="{{ blog.thumbnail.url }}"></a> ({{blog.title}})--> 
     
     <div  data-aos="fade-up">
      
        <div class="container mt-10 mx-auto p-4 md:p-0 relative hover:scale-105 transition duration-500">

          <!-- Card wrapper -->
          <div class="flex flex-wrap w-full lg:w-4/5 mx-auto">
            
            <!-- Card image -->
            <div class="bg-cover rounded-tl-3xl bg-bottom border border-white w-full md:w-1/3 h-64 md:h-auto relative hover:opacity-90 transition duration-100" style="background-image:url('{{blog.thumbnail.url}}')">
              <div class="absolute text-xl">
                <i class="fa fa-heart text-white hover:text-red-light ml-4 mt-4 cursor-pointer"></i>
              </div>
            </div>
            <!-- ./Card image -->
            
            <!-- Card body -->
            <div class="myclass w-full md:w-2/3">
              <!-- Card body - outer wrapper -->
              <div class="h-full mx-auto px-6 md:px-0 md:pt-6 md:-ml-6 relative ">
                <!-- Card body - inner wrapper -->
                <div class="bg-inherit border border-white lg:h-full p-6 -mt-6 md:mt-0 relative mb-4 md:mb-0 flex flex-wrap md:flex-wrap items-center rounded-tr-3xl">
                  <!-- Card title and subtitle -->
                  <div class="w-full lg:w-3/4 lg:border-right lg:border-solid text-center md:text-left">
                    <strong style="color: white;">Title: {{blog.title}}</strong>
                    <div class="flex items-center py-2">
                      <img class="w-10 h-10 rounded-full mr-4" src="{{blog.author.profile.profile_pic.url}}" alt="Avatar of Writer">
                      <div class="text-sm">
                        <p class="text-gray-100 leading-none">{{blog.author.username}}</p>
                        <p class="text-gray-100">{{blog.created_date}}</p>
                      </div>
                    </div>
                    <hr class="w-1/4 md:ml-0 mt-4  border lg:hidden">
                  </div>
                  <!-- ./Card title and subtitle -->
                  
                  <!-- Card description -->
                  <div class="w-full lg:w-4/5 lg:px-4 lg:py-4">
                    <p class="text-md mt-4 lg:mt-0 text-justify md:text-left text-sm text-gray-100">
                   {{blog.description | truncatewords:10 }}
                    </p>
                  </div>
                  <!-- ./Card description -->
                  
                  <!-- Call to action button -->
                  
                  <div class="w-full lg:w-1/5 mt-6 lg:mt-0 lg:px-4 text-center">
                    <a href="{% url 'blogview' blog.id %}">  <button class="bg-none hover:bg-gray-300 border border-white w-1/3 lg:w-full   py-2 text-gray-100 hover:text-gray-900 transition duration-100">Read now</button>  </a>
                  </div>
                
                  <!-- ./Call to action button -->
                </div>
                <!-- ./Card body - inner wrapper -->
              </div>
              <!-- ./Card body - outer wrapper -->
            </div>
            <!-- ./Card body -->
          </div>
          <!-- ./Card wrapper -->
        </div>
        <!-- ./Container -->
      
  
    </div>
  
    {% endfor %}
  </section>
  {% else %}
    <p>There are no blogs.</p>
  {% endif %}
{% endblock %}

{%block myscript %}

{% endblock myscript %}

blog/templates/blog/blogpost_view.html
{% extends "main.html" %}
{% block title %}
{{object.title}} 
{% endblock title %}

{% block myblock %}
<style>
  fieldset {
  border: 0;
  background: #222;
  border-radius: 1px;
  padding: 1em 1.5em 0.9em;
  margin: 1em auto;
 
}
.star-cb-group {
  /* remove inline-block whitespace */
  font-size: 0;
  /* flip the order so we can use the + and ~ combinators */
  unicode-bidi: bidi-override;
  direction: rtl;
  /* the hidden clearer */
}
.star-cb-group * {
  font-size: 1rem;
}
.star-cb-group > input {
  display: none;
}
.star-cb-group > input + label {
  /* only enough room for the star */
  display: inline-block;
  overflow: hidden;
  text-indent: 9999px;
  width: 1em;
  white-space: nowrap;
  cursor: pointer;
  font-size:40px;
}
.star-cb-group > input + label:before {
  display: inline-block;
  text-indent: -9999px;
  content: "☆";
  color: #888;
}
.star-cb-group > input:checked ~ label:before, .star-cb-group > input + label:hover ~ label:before, .star-cb-group > input + label:hover:before {
  content: "★";
  color: #e52;
  text-shadow: 0 0 1px #333;
}
.star-cb-group > .star-cb-clear + label {
  text-indent: -9999px;
  width: .5em;
  margin-left: .5em;
}
.star-cb-group > .star-cb-clear + label:before {
  width: .5em;
}
.star-cb-group:hover > input + label:before {
  content: "☆";
  color: #888;
  text-shadow: none;
}
.star-cb-group:hover > input + label:hover ~ label:before, .star-cb-group:hover > input + label:hover:before {
  content: "★";
  color: #e52;
  text-shadow: 0 0 1px #333;
}


</style>

<style>
  .mycontainer{
    padding-top:50px;
  }

  
</style>



{% endblock myblock %}
{% block content %}


<section class="mycontainer">
<section class="inner-page">
  
    <section id="events"  class="events" style="background-image: url({{object.thumbnail.url}}) ">
      <div class="container" data-aos="fade-up">
    
        <div class="section-title">
          <p style = " font-size: 50px;">{{object.title}}</p>
        </div>
    
        <div class="events-slider swiper" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper" >
  
  
           
  {% for imag in object.blogimages_set.all %} 
  
  <div class="swiper-slide">
    <div class="row event-item">
     
        <img src="{{imag.image.url}}" class="img-fluid" alt="">
    
    </div>
  </div>
  
  {% endfor %}
</div>
<div class="swiper-pagination"></div>
</div>

</div>
</section>

 



  <div class="container" data-aos="fade-up">

    <p style="padding-top:20px;"> <strong>Author:</strong> <br>{{ object.author }}</p> 
    <p style="padding-top:10px;"> <strong>Posted on:</strong> <br>{{ object.created_date }}</p> 
  <p style="padding:10px;">{{ object.description | linebreaks }}</p>
</div>
</section>

 
  
</section>
{% endblock %}





{% block myscript %}
<script>
  
 
</script>
{% endblock myscript %}

blog/templates/blog/postblog.html
{% extends "main.html" %}

{% block title %}
{{place.name}}-post blog}
{% endblock title %}
{% block myblock %}

<style>
textarea:focus,
.form-select:focus,
input[type="text"]:focus,
input[type="password"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="time"]:focus,
input[type="week"]:focus,
input[type="number"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="search"]:focus,
input[type="tel"]:focus,
input[type="color"]:focus,
input[type='file']:focus,
input[type="checkbox"]:focus,
.uneditable-input:focus {   
  border-color: rgb(255, 255, 255);
  box-shadow: 0 1px 1px rgba(255, 255, 255, 0.075) inset, 0 0 8px rgba(250, 250, 250, 0.6);
  outline: 0 none;
  
}



.profile-button {
            background: rgb(99, 39, 120);
            box-shadow: none;
            border: none;
            padding: 10px 20px;
            text-align: center;
        }
        
        .profile-button:hover {
            background: #682773
        }
        
        .profile-button:focus {
            background: #682773;
            box-shadow: none
        }
        
        .profile-button:active {
            background: #682773;
            box-shadow: none
        }

.form-control{
  background-color: rgba(255,255,255,0.75);
}


        
</style>

{% endblock %}

{% block content %}

<section>
    <section class="inner-page">
<section id="book-a-table" class="book-a-table">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>Add blog</h2>
        <p>Post a blog</p>
      </div>

      <form method="POST" class=" myform" data-aos="fade-up" enctype="multipart/form-data" data-aos-delay="100">
        {% csrf_token %}
        
          <div class="form-group">
            {{form.title}}
          </div>
          
         
      
        <div class="form-group mt-3">
            <textarea class="form-control" name="post" rows="5" placeholder="Blog content..."></textarea>
        </div>
        
          <div class="row">
          <div class=" col-6 form-group mt-3">
              <p style="color:#cda45e; font-size: 15px;">Thumbnail image:</p>
            {{form.thumbnail}}
          </div>
          <div class=" col-6 form-group mt-3">
            <p style="color:#cda45e; font-size: 15px;">Blog images:<p>
        <input type="file" multiple name="images"/>
    </div>
    </div>
        
        <div class="text-center"><button type="submit" class="profile-button">Post</button></div>
      </form>

    </div>
</section>
</section>
</section>
{% endblock %}


{% block myscript %}

<script>
var form_fields = document.getElementsByTagName('input')
form_fields[1].placeholder='Blog title';




form_fields[1].className += ' form-control'
form_fields[2].className += ' form-control'
form_fields[3].className += ' form-control'



</script>


{% endblock myscript %}