blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.bloglistview.as_view(), name='bloglist'),
    path('<int:pk>', views.blogdetailview.as_view(), name='blogview'),
    
]

destination/urls.py
from django.urls import path
from . import views
from blog.views import add_blogview
from destination.views import Rateview

urlpatterns = [
    path('',views.placelistview.as_view(), name='placelist'),
    path('<int:pk>/', views.placedetailview, name='placeview'),
    path('addblog/<int:p_id>/',add_blogview,name='blogadd'),
    path('rate/<int:r_id>/',Rateview,name='rate-place'),
   # path('celery/', test , name='celery'),
    
]

ourproject/urls.py
from atexit import register
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from login.views import loginpage,logoutpage
from registration.views import registerpage,accountsetting

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('075bct/', admin.site.urls),
    path('',loginpage,name='login'),
    path('registerpage/', registerpage,name="registerpage"),
    path('ac/',accountsetting,name='as'),
   ## path('',include('home.urls')),
    path('mainpage/',include('main.urls')),
       
    
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

destination/models.py
from django.urls import reverse 
from django.db import models
import datetime
from django.contrib.auth.models import User
from ratinghome.models import Rateinfo 
from django.utils import timezone
import os

def content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.name, 'thumbnail', ext)
    return os.path.join('thumbnails', filename)

# Create your models here.
class Places(models.Model):
    name=models.CharField(max_length=100,null=True,blank=True)
    address=models.CharField(max_length=30)
    descrption=models.TextField(default="")
    thumbnail_image=models.ImageField(upload_to=content_file_name,default = 'thumbnail_default.jpg')
    ispopular = models.BooleanField(default=False)
    rateinfo = models.OneToOneField(Rateinfo, on_delete=models.CASCADE)
    def get_absolute_url(self):      
        return reverse('placeview', args=[str(self.id)])
    def __str__(self):
        return self.name
    
class Place_rating(models.Model):
    rate=models.PositiveSmallIntegerField(choices=[(1,1),(2,2),(3,3),(4,4),(5,5)],default=0) 
    place=models.ForeignKey(Places,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return "%s-%s" % (self.user.username,self.place.name)


class Comment(models.Model):
    place=models.ForeignKey(Places,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    comment_body= models.TextField()
    created_date=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-created_date']
    
    def __str__(self):
        return '%s -  %s' %(self.place.name,self.user.username)

def img_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s_%s.%s" % (instance.place.name, 'image', ext)
    return os.path.join('thumbnails', filename)


class Destimages(models.Model):
    place=models.ForeignKey(Places,on_delete=models.CASCADE)
    image=models.ImageField(upload_to=img_file_name )

    def __str__(self):
        return self.place.name



class Hotel(models.Model):
    title=models.CharField(max_length=20)
    contact_info=models.CharField(max_length=15)
    nearby=models.ForeignKey(Places,on_delete=models.CASCADE)

    def __str__(self):
        return self.nearby.name



class Mf_result(models.Model):
    rate=models.FloatField() 
    place=models.ForeignKey(Places,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return "%s-%s" % (self.user.username,self.place.name)
   




        

destination/forms.py
from django import forms
from .models import Comment,Place_rating 

class comment_form(forms.ModelForm):
    class Meta:
        model=Comment 
        fields=['comment_body']

rate_choices=[(1,1),(2,2),(3,3),(4,4),(5,5)]

class rateform(forms.ModelForm):
    Choice=[
        (1,1),
           (2,2),
        (3,3),
           (4,4),
         (5,5)]
    rate=forms.ChoiceField(choices=Choice,widget=forms.RadioSelect)
    class Meta:
        model=Place_rating
        fields=['rate']

destination/views.py
from audioop import reverse
from multiprocessing import context
from re import template
from unittest import loader
from django.shortcuts import get_object_or_404, redirect, render,HttpResponseRedirect
from .models import Places,Place_rating
from django.views import View, generic
from .models import Destimages, Comment
from django.db.models import Q
from django.views.generic import FormView 
from django.views.generic.detail import SingleObjectMixin 
from .forms import comment_form,rateform
from django.urls import reverse_lazy 
from django.contrib import messages
from django.contrib.auth.decorators import login_required 
from django.utils.decorators import method_decorator
from recommender.views import hybrid_recommender
from ratinghome.models import Rateinfo
from registration.models import Profile


@method_decorator(login_required, name='dispatch')
class placelistview(generic.ListView):
    model= Places
    template_name= 'destination/place_list.html'
    context_object_name = 'object'

    # The get_context_data method is used to customize the view's context data, which includes the top recommendations, other recommendations, and a list of popular places.
  
    def get_context_data(self, **kwargs):
        recommendations = hybrid_recommender(self.request.user)
        
        if len(recommendations)==2:
            top = recommendations[0]
            other = recommendations[1]
            popularlist= Places.objects.filter(ispopular=True)
            topqueryset = Places.objects.filter(rateinfo__pID__in = top)
            otherqueryset = Places.objects.filter(rateinfo__pID__in = other)
            context = super(placelistview, self).get_context_data(**kwargs)
            context.update({
                'top' : sorted(topqueryset, key=lambda x: top.index(x.rateinfo.pID)),
                'recommendations': sorted(otherqueryset, key=lambda x: other.index(x.rateinfo.pID)),
                'popular' : sorted(popularlist, key = lambda x : x.name),
            })
            return context
        else:
            queryset= Places.objects.filter(rateinfo__pID__in=recommendations)
            popularlist= Places.objects.filter(ispopular=True)
       
            context = super(placelistview, self).get_context_data(**kwargs)
            context.update({
                'top' : [],
                'recommendations': sorted(queryset, key=lambda x: recommendations.index(x.rateinfo.pID)),
                'popular' : sorted(popularlist, key = lambda x : x.name),
            })
            return context
    

# placedetailview, is a function-based view that displays the details of a specific travel destination. It also allows users to leave comments on the destination. If a comment is submitted, the view saves it to the database and displays the updated destination details.   
@login_required
def placedetailview(request,pk):
    place=get_object_or_404(Places,id=pk)
    guide= Profile.objects.filter( place=pk)
    comment = request.POST.get('msg')
    if comment== None or len(comment)==0:
        data=Places.objects.get(id=pk)         
        return render(request,'destination/place_view.html',{'data':data , 'guides':guide}) 

    else :
        data= Comment()
        data.user= request.user
        data.place_id=pk
        data.comment_body = comment
        data.save()
        data=Places.objects.get(id=pk)         
        return render(request,'destination/place_view.html',{'data':data, 'guides':guide }) 


@login_required
def Rateview(request, r_id):
     url = request.META.get('HTTP_REFERER')
     if request.method == 'POST':
        try:
            rating = Place_rating.objects.get(user__id=request.user.id, place__id=r_id)
            form = rateform(request.POST, instance=rating)
            form.save()
            
            return redirect('placeview', r_id)
        except Place_rating.DoesNotExist:
            form = rateform(request.POST)
            if form.is_valid():
                data = Place_rating()
                data.rate = form.cleaned_data['rate']
                data.place_id = r_id
                data.user_id = request.user.id
                data.save()
               
                return redirect(url)

destination/templates/destination/place_list.html
{% extends 'mainpage.html' %}
{% load static %}
{% block myblock %}
<script src="https://cdn.tailwindcss.com"></script>
{% endblock myblock %}

{% block content %}

  
  
  
 <section>

  <section id="events" class="events">
    <div class="container" data-aos="fade-up">
  
      <div class="section-title">
        <p style = " font-size: 50px; ">Popular Destinations</p>
      </div>
  
      <div class="events-slider swiper" data-aos="fade-up" data-aos-delay="100">
        <div class="swiper-wrapper">
          
    {% if popular %}

  

    {% for place in popular %}
    
      
      <!-- <a href="{% url 'placeview' place.id %}"> <img style="width:200px;height:200px;" src="{{ place.thumbnail_image.url }}">
            <br><p>({{place.name}})</p></a> --> 
            
         
                  
            <div class="swiper-slide">
              <div class="row event-item">
                <div class="col-lg-6">
                  <img style="max-height: 300px; min-width:100%;" src="{{place.thumbnail_image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-lg-6 pt-4 pt-lg-0 content">
                  <h3>{{place.name}}</h3>
                  <br>
                  <p>
                    {{place.descrption|truncatewords:30}}
                  </p>
                  <div class="price">
                    <a href="{% url 'placeview' place.id %}" style = "color: white;"><p style="padding-top: 100px;"><span >Visit Now</span></p></a>
                  </div>
                 
                  
               
                </div>
              </div>
            </div>
               
   
    {% endfor %}
    {% else %}
    <p>There are no popular places.</p>
  {% endif %}
  </div>
  <div class="swiper-pagination"></div>
</div>

</div>
</section>

</section>


{% if top %}

<div class="container" data-aos="fade-up">
  <div class="container px-2 py-2 mx-auto">
  <div class="section-title">
    <h2>Top Recommendations</h2>
    
  </div>
  
      
  <div class="text-gray-600 body-font">
    
      <div class="flex flex-wrap -m-4">
    {% for place in top %}
   
          <div class="py-3 px-3 md:w-1/3">
            <div class="member" data-aos="zoom-in" data-aos-delay="100">
            <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden ">
              <a href="{{place.thumbnail_image.url}}" class="gallery-lightbox" data-gall="gallery-item">
              <img class="lg:h-48 md:h-36 w-full object-cover object-center transition duration-100 hover:opacity-60 hover:cursor-pointer transition duration-200" src="{{place.thumbnail_image.url}}" alt="thumbnail">
              </a>
              <div class="p-6">
                <h1 class="title-font text-lg font-medium text-gray-100 mb-3">{{place.name | truncatewords:5}}</h1>
                <p class="leading-relaxed mb-3">{{place.descrption | truncatewords:10 }}</p>
                <div class="flex items-center flex-wrap ">
                  <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0" href="{% url 'placeview' place.id %}">Visit Now
                    <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path d="M5 12h14"></path>
                      <path d="M12 5l7 7-7 7"></path>
                    </svg>
                  </a>
                </div>
              </div>
            </div>
            </div>
          </div>
        
    {% endfor %}
        </div>
  </div>
  </div>
  </div>

{% endif %}



<div class="container pt-4" data-aos="fade-up">
  <div class="container px-2 py-2 mx-auto">
    
<div class="section-title">
  <h2>Recommendations for You</h2>
  
</div>

    
<div class="text-gray-600 body-font">
  
    <div class="flex flex-wrap -m-4">
  {% for place in recommendations %}
 
        <div class="py-3 px-3 md:w-1/3">
          <div class="member" data-aos="zoom-in" data-aos-delay="100">
          <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden ">

            <a href="{{place.thumbnail_image.url}}" class="gallery-lightbox" data-gall="gallery-item">
              
            <img class="lg:h-48 md:h-36 w-full object-cover object-center transition duration-100 hover:opacity-60 hover:cursor-pointer transition duration-200" src="{{place.thumbnail_image.url}}" alt="thumbnail">
            </a>
            <div class="p-6">
              <h1 class="title-font text-lg font-medium text-gray-100 mb-3">{{place.name | truncatewords:5}}</h1>
              <p class="leading-relaxed mb-3">{{place.descrption | truncatewords:10 }}</p>
              <div class="flex items-center flex-wrap ">
                <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0" href="{% url 'placeview' place.id %}">Visit Now
                  <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M5 12h14"></path>
                    <path d="M12 5l7 7-7 7"></path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
          </div>
        </div>
      
  {% endfor %}
      </div>
</div>
</div>
</div>


  {% endblock content %}


 

 

destination/templates/destination/place_view.html
{% extends "main.html" %}

{% block title %}
{{data.name}} : Details
{% endblock title %}


{% block myblock %}
<style>
  fieldset {
    border: 0;
    background: #222;
    border-radius: 1px;
    padding: 1em 1.5em 0.9em;
    margin: 1em auto;

  }

  .star-cb-group {
    /* remove inline-block whitespace */
    font-size: 0;
    /* flip the order so we can use the + and ~ combinators */
    unicode-bidi: bidi-override;
    direction: rtl;
    /* the hidden clearer */
  }

  .star-cb-group * {
    font-size: 1rem;
  }

  .star-cb-group>input {
    display: none;
  }

  .star-cb-group>input+label {
    /* only enough room for the star */
    display: inline-block;
    overflow: hidden;
    text-indent: 9999px;
    width: 1em;
    white-space: nowrap;
    cursor: pointer;
    font-size: 40px;
  }

  .star-cb-group>input+label:before {
    display: inline-block;
    text-indent: -9999px;
    content: "☆";
    color: #888;
  }

  .star-cb-group>input:checked~label:before,
  .star-cb-group>input+label:hover~label:before,
  .star-cb-group>input+label:hover:before {
    content: "★";
    color: #e52;
    text-shadow: 0 0 1px #333;
  }

  .star-cb-group>.star-cb-clear+label {
    text-indent: -9999px;
    width: .5em;
    margin-left: .5em;
  }

  .star-cb-group>.star-cb-clear+label:before {
    width: .5em;
  }

  .star-cb-group:hover>input+label:before {
    content: "☆";
    color: #888;
    text-shadow: none;
  }

  .star-cb-group:hover>input+label:hover~label:before,
  .star-cb-group:hover>input+label:hover:before {
    content: "★";
    color: #e52;
    text-shadow: 0 0 1px #333;
  }
</style>

<style>
  .commentcontainer {
    padding-top: 20px;
  }

  .mycontainer {
    padding-top: 50px;
  }

  .merodiv {
    text-align: right;
  }


  #clicked {
    padding-top: 1px;
    padding-bottom: 1px;
    text-align: center;
    width: 100%;
    background-color: #ecb21f;
    border-color: #a88734 #9c7e31 #846a29;
    color: black;
    border-width: 1px;
    border-style: solid;
    border-radius: 13px
  }

  #profile {
    background-color: unset
  }

  #post {
    margin: 8px;
    padding: 8px;

    text-align: center;
    background-color: #ecb21f;
    border-color: #a88734 #9c7e31 #846a29;
    color: black;
    border-width: 1px;
    border-style: solid;
    border-radius: 13px;
    width: 25%;

  }

  #profile {
    text-decoration: none;
    color: rgb(224, 219, 219);
    background-color: black
  }

  .comments {
    margin-top: 5%;
    margin-left: 20px
  }

  .darker {
    border: 1px solid #ecb21f;
    background-color: black;
    float: right;
    border-radius: 5px;
    padding-left: 40px;
    padding-right: 30px;
    padding-top: 10px
  }

  .comment {
    border: 1px solid rgba(16, 46, 46, 1);
    background-color: rgba(16, 46, 46, 0.973);
    float: left;
    border-radius: 5px;
    padding-left: 40px;
    padding-right: 30px;
    padding-top: 10px
  }

  .comment h4,
  .comment span,
  .darker h4,
  .darker span {
    display: inline
  }

  .comment p,
  .comment span,
  .darker p,
  .darker span {
    color: rgb(184, 183, 183)
  }


  h4 {
    color: white;

    font-size: 20px;
  }

  label {
    color: rgb(212, 208, 208)
  }

  #align-form {
    margin-top: 20px
  }

  .form-group p a {
    color: white
  }

  #checkbx {
    background-color: black
  }

  #darker img {
    margin-right: 15px;
    position: static
  }


  .form-control:focus {
    background-color: rgba(255, 255, 255, 0.9);
  }

  .form-group input,
  .form-group textarea {
    background-color: black;
    border: 1px solid rgba(16, 46, 46, 1);
    border-radius: 12px;
    color: rgb(168, 167, 167);
  }

  .commentform {
    border: 1px solid #ecb21f;

    border-radius: 5px;
    padding: 20px
  }

  .submitbutton {
    margin-top: 8px;
    padding-top: 8px;
    padding-bottom: 8px;

    text-align: center;
    background-color: #cda45e;
    border-color: white;
    color: black;
    border-width: 1px;
    border-style: solid;
    border-radius: 13px;
    width: 25%;
  }

  .guideRow {
    display: flex;
    flex-direction: column;
    border: 1px solid #ecb21f;
    border-radius: 13px;
    margin: 20px 0 20px 0;
    padding: 10px 15px;
    cursor: pointer;


  }

  /* .guidelist {
    display: flex;

    gap: 2rem;
    padding: 10px 15px;
    text-transform: capitalize;
    text-align: center;
    align-items: center;
  } */

  .guideTitle {
    display: flex;
    position: relative;
    ;
  }

  .guideHeading {
    width: 100%;
    margin: 0 20px;
    display: flex;
    text-align: center;
    align-items: center;
    /* justify-content: space-around; */
  }

  .guideHeading h4::before {
    content: '+';
    position: absolute;
    color: #cda45e;
    top: 50%;
    right: 50px;
    font-size: 40px;
    transform: translateY(-50%);
  }

  .guideRow.active .guideHeading h4::before {
    content: '-';
  }

  .guidebutton {

    padding: 10px 15px;
    text-align: center;
    background-color: #cda45e;
    border-color: white;
    color: black;
    border-width: 1px;
    border-style: solid;
    border-radius: 13px;
  }

  .guideRow #guideDetails {
    margin-left: 9%;
    text-transform: capitalize;
    position: relative;
    height: 0;
    overflow: hidden;
    transition: 0.5s;
    overflow-y: auto;
  }

  .guideRow.active #guideDetails {
    height: 180px;
  }
</style>



{% endblock myblock %}
{% block content %}


<section class="mycontainer">
  <section class="inner-page">

    <section id="events" class="events" style="background-image: url({{data.thumbnail_image.url}}) ">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <p style=" font-size: 50px;">{{data.name}}</p>
        </div>

        <div class="events-slider swiper" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            {% if data.destimages_set.all %}

            {% for imag in data.destimages_set.all %}

            <div class="swiper-slide">
              <div class="row event-item">

                <img src="{{imag.image.url}}" class="img-fluid" alt="">

              </div>
            </div>

            {% endfor %}

            {% endif %}
          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section>





    <div class="container" data-aos="fade-up">

      <p style="padding-top:20px;"> <strong>Address:</strong> <br>{{ data.address }}</p>

      <p><strong>Description:</strong> {{ data.descrption | linebreaks }}</p>
    </div>
  </section>

  <div class="container" data-aos="fade-up">
    <h2 style="text-align: right">HOW DO YOU RATE THIS PLACE?</h2>
    <form method="POST" action="{% url 'rate-place' data.id %}" class="merodiv">
      {% csrf_token %}
      <!--rating the place with star   -->
      <div class="star-cb-group">
        <input type="radio" name="rate" id="rating5" value="5" required /><label for="rating5" title="5"></label>
        <input type="radio" name="rate" id="rating4" value="4" required /><label for="rating4" title="4"></label>
        <input type="radio" name="rate" id="rating3" value="3" required /><label for="rating3" title="3"></label>
        <input type="radio" name="rate" id="rating2" value="2" required /><label for="rating2" title="2"></label>
        <input type="radio" name="rate" id="rating1" value="1" required /><label for="rating1" title="1"></label>

      </div>

      <div class="form-group"><button type="submit" class="btn  submitbutton">submit rating</button></div>

    </form>
  </div>



  <div class="container commentcontainer" data-aos="fade-up">

    <a href="{% url 'blogadd' data.id %}" style="font-size: 30px;">ADD BLOG +</a>
    <div class="row">


      <div class=" col-12 mt-4">
        <form id="align-form" method="POST" class="commentform">
          {% csrf_token %}
          <div class="form-group">
            <h4>Leave a comment</h4> <label for="message">Comment:</label> <textarea name="msg" id="msg" cols="30"
              rows="5" class="form-control"></textarea>
          </div>

          <div class="form-group "> <button type="submit" id="post" class="btn">Post Comment</button> </div>
        </form>
      </div>




      <div class="col-12 pb-4 pt-4">
        <h3>Comments:</h3>
        {% for comment in data.comment_set.all %}
        <div class="row">


          <div class="text-justify darker mt-4 col-12"> <img src="{{ comment.user.profile.profile_pic.url }}" alt=""
              class="rounded-circle" width="40" height="40">
            <h4>{{ comment.user.username }}</h4> <span>- {{comment.created_date|date:"M d, Y"}}</span> <br>
            <div class="pt-2" style="padding-left: 4px;">
              <p>{{ comment.comment_body }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

    <div class="col-12 pb-4 pt-4">
      <h3>Available Guides</h3>
      {% for guide in guides %}
      <!-- <div class="guideRow">
        <div class="guidelist">
          <img src="{{ guide.profile_pic.url }}" alt="" class="rounded-circle" width="80" height="80">
          <a href="{% url 'index' %}">
            <h4>{{ guide.user.username }}</h4>
          </a>
          <div class="text-gray-400">

          {% comment %} new changes {% endcomment %}
          <div class="grid md:grid-cols-1 text-sm">
            <div class="grid grid-cols-2">
              <div class="px-4 py-2 font-semibold">First Name</div>
              <div class="px-4 py-2">{{guide.user.first_name}}</div>
            </div>

            <div class="grid grid-cols-2">
              <div class="px-4 py-2 font-semibold">Last Name</div>
              <div class="px-4 py-2">{{guide.user.last_name}}</div>
            </div>
            <div class="grid grid-cols-2">
              <div class="px-4 py-2 font-semibold">Gender</div>
              <div class="px-4 py-2">{{guide.user.profile.sex}}</div>
            </div>
            <div class="grid grid-cols-2">
              <div class="px-4 py-2 font-semibold">Age</div>
              <div class="px-4 py-2">{{guide.user.profile.age}}</div>
            </div>
            <div class="grid grid-cols-2">
              <div class="px-4 py-2 font-semibold">Contact No.</div>
              <div class="px-4 py-2">{{guide.user.profile.phone_number}}</div>
            </div>
            <div class="grid grid-cols-2">
              <div class="px-4 py-2 font-semibold">Email</div>
              <div class="px-4 py-2">{{guide.user.email}}</div>
            </div>
            {% comment %} new changes ends {% endcomment %}

          </div>
        </div>
        {% endfor %}
      </div> -->
      {% for guide in guides %}
      <div class="guideRow">
        <div class="guideTitle">
          <div class="guideImage">
            <img src="{{ guide.profile_pic.url }}" alt="" class="rounded-circle" width="80" height="80">
          </div>
          <div class="guideHeading">
            <h4>{{ guide.user.username }}</h4>
            <!-- <button class="guidebutton" onclick=showDetails()>Details</button> -->
          </div>
        </div>
        <div id="guideDetails">
          <div>
            <p>Name: {{guide.user.first_name}} {{guide.user.last_name}}</p>
            <p>Gender: {{guide.user.profile.sex}}</p>
            <p>Age: {{guide.user.profile.age}}</p>
            <p>Contact No: {{guide.user.profile.phone_number}}</p>
            <!-- <p>Email: {{guide.user.email}}</p> -->
            {% comment %} <button class="guidebutton">Email</button> {% endcomment %}
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
</section>
{% endblock %}





{% block myscript %}
<script>
  // const guideDetailContainter = document.getElementById("guideDetails");
  // let isClicked = true
  // let showDetails = function () {
  //   if (isClicked) {
  //     guideDetailContainter.style.display = "block";
  //     isClicked = false
  //   } else {
  //     guideDetailContainter.style.display = "none";
  //     isClicked = true;
  //   }
  // }
  const accordion = document.getElementsByClassName("guideRow")
  for (i = 0; i < accordion.length; i++) {
    accordion[i].addEventListener("click", function () {
      this.classList.toggle("active")
    })
  }
</script>
{% endblock myscript %}